### ISSUE TITLE
Feather

### ISSUE THREAD

**Issue by TheRealBLP** [ViaVersion/ViaFabricPlus#172] opened 2023-07-08 10:15 UTC
### General Information

The mod ViafabricPlus is incompatible with Feather or at least most versions of viafabricplus, in 1.20 and 1.21 Minecraft just doesnt want to start and in 1.19.4 it only works in the version 2.6.8 of the mod. Any ideas how to fix this? I tried it also without any mods except viafabricplus

### Bug Description

It just doesnt start

### Steps to Reproduce

Use the mod with feather client

### Expected Behavior

The game should start

**Comment by RaphiMC** [comment] 2023-07-08 10:42
Duplicate of #157

**Closed by RaphiMC** 2023-07-08 10:42 UTC
Labels: bug
