### ISSUE TITLE
Cannot join Bedrock server (1.20.80.05)

### ISSUE THREAD

**Issue by NightGush** [ViaVersion/ViaFabricPlus#416] opened 2024-05-15 04:20 UTC
### General Information

https://dump.viaversion.com/4151fba7f0ba2c6e9bf61d4dd3026ef4edc485b37ecdeffcf2ffe4dc237e6d23

### Bug Description

When I join my bedrock server (running MC Bedrock 1.20.80.05), I (using Java 1.20.6) get an error: `Internal Exception: io.netty.handler.codecDecoderException: Pipeline has no inbound protocol configured, can't process packet PooledUnsafeDirectByteBuf(freed)`

In my server logs, it shows that I quickly joined and disconnected from the server.

When I host a clean 1.20.80.05 server on localhost, it still doesn't let me join, so it isn't a problem with the server.

I am using Linux and PrismLauncher if that makes any difference

### Steps to Reproduce

1. Join a 1.20.80.05 Bedrock server using Java 1.20.6
2. Get the error `Internal Exception: io.netty.handler.codecDecoderException: Pipeline has no inbound protocol configured, can't process packet PooledUnsafeDirectByteBuf(freed)`

### Expected Behavior

I should be able to join the server and not get that error

**Comment by NightGush** [comment] 2024-05-15 05:08
I just checked, downgrading my Java version to 1.20.4 makes it work.

**Comment by pythonmcpi** [comment] 2024-05-15 06:23
I'm able to replicate this issue on ViaFabricPlus 3.2.1 with Minecraft 1.20.6.

**Comment by RaphiMC** [comment] 2024-05-15 07:20
Duplicate of #414

**Closed by RaphiMC** 2024-05-15 07:20 UTC
Labels: bug
