### ISSUE TITLE
Can't log in the 1.19.4 server

### ISSUE THREAD

**Issue by 12345-mcpython** [ViaVersion/ViaFabricPlus#351] opened 2024-02-14 03:04 UTC
### General Information

ViaFabricPlus: 3.0.6
Fabric API: 0.96.1
Minecraft: 1.20.4

### Bug Description

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/63326494/a3e4a0cf-4806-42a9-b8d2-a091c9f19ce6)

### Steps to Reproduce

1. Joining server "2b2t.xin"
2. Right click the compass to join in the server

### Expected Behavior

no error

**Comment by 12345-mcpython** [comment] 2024-02-14 03:13
It may be the server error. I'll check it.

**Comment by FlorianMichael** [comment] 2024-02-18 17:01
Can't reproduce this, which server are you trying to join?

**Comment by 12345-mcpython** [comment] 2024-02-24 07:52
> Can't reproduce this, which server are you trying to join?

I wrote in description. It's "2b2t.xin"

**Comment by FlorianMichael** [comment] 2024-05-26 17:54
Can't reproduce on latest ViaFabricPlus (3.0.0). Closing.

**Closed by FlorianMichael** 2024-05-26 17:54 UTC
Labels: bug
