### ISSUE TITLE
1.20.6 to 1.21 is very buggy

### ISSUE THREAD

**Issue by User-B4538** [ViaVersion/ViaFabricPlus#462] opened 2024-06-26 01:28 UTC
### General Information

Now there is a very good chance Im doing something wrong, but I am having a bad experience when connecting to a 1.21 server from a 1.20.6 client. Now the problem could be that the server doesn't have via fabric, but from what i've been able to find that was not a problem mentioned

### Bug Description

- cant place boats
- cant collect water from buckets or bottles
- cant trade with villagers

### Steps to Reproduce

.

### Expected Behavior

.

**Comment by seriousfreezing** [comment] 2024-06-26 18:49
From what I've tested, it's incompatible with Bedrockify, which is why it crashes every time I try to use it

**Comment by FlorianMichael** [comment] 2024-06-26 18:50
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/451, see my answer there for a solution. 

@seriousfreezing This issue has nothing to do with Bedrockify, please make your own issue.

**Closed by FlorianMichael** 2024-06-26 18:50 UTC
Labels: bug
