### ISSUE TITLE
Latest Release [v2.9.5] crashes with NoChatReports

### ISSUE THREAD

**Issue by ManifestJW** [ViaVersion/ViaFabricPlus#299] opened 2023-11-27 08:48 UTC
### General Information

animatica: Animatica 0.6+1.20
		betterf3: BetterF3 8.0.2
		bettermounthud: Better Mount HUD 1.2.2
		borderlessmining: Borderless Mining 1.1.9+1.20.2
		capes: Capes 1.5.3+1.20.2
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		cloth-config: Cloth Config v12 12.0.111
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.4+1.20.2
		controlify: Controlify 1.7.0+1.20.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0
			dev_isxander_libsdl4j: libsdl4j 2.28.2-11
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_quilt-json5: quilt-json5 1.0.3
		debugify: Debugify 1.20.2+1.0
		dynamic_fps: Dynamic FPS 3.2.1
		e4mc_minecraft: e4mc 4.0.1
		enhancedblockentities: Enhanced Block Entities 0.9.1+1.20.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.8.0
			spruceui: SpruceUI 5.0.3+1.20.2
		entity_model_features: Entity Model Features 1.1.0
		entity_texture_features: Entity Texture Features 4.6.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		fabric-api: Fabric API 0.91.0+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.76+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.6+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.0+6225d43aa0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.9+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.7+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.42+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.11+9ab11d52a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabric-language-kotlin: Fabric Language Kotlin 1.10.15+kotlin.1.9.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.1
		fabricloader: Fabric Loader 0.14.24
		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.2
		fabrishot: Fabrishot 1.10.0
		fastquit: FastQuit 3.0.0+1.20+
		ferritecore: FerriteCore 6.0.1
		fsb-interop: FabricSkyBoxes Interop 1.3.6+mc1.20.2-build.52
		immediatelyfast: ImmediatelyFast 1.2.7+1.20.2
			net_lenni0451_reflect: Reflect 1.3.0
		indium: Indium 1.0.27+mc1.20.1
		iris: Iris 1.6.10
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		isxander-main-menu-credits: Main Menu Credits 1.1.2
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.3+1.20.2
			pride: Pride Lib 1.2.0+1.19.4
		languagereload: Language Reload 1.5.10+1.20.2
		lithium: Lithium 0.12.0
		minecraft: Minecraft 1.20.2
		mixintrace: MixinTrace 1.1.1+1.17
		modelfix: Model Gap Fix 1.14
		modernfix: ModernFix 5.9.3+mc1.20.2
		modmenu: Mod Menu 8.0.0
		morechathistory: MoreChatHistory 1.1.1
		moreculling: More Culling 1.20.1-0.19.0
			conditional-mixin: conditional mixin 0.3.2
		nochatreports: No Chat Reports 1.20.2-v2.3.1
		optigui: OptiGUI 2.1.6
			optiglue: OptiGlue 2.1.6-mc.1.19.3
			org_apache_commons_commons-text: commons-text 1.10.0
			org_ini4j_ini4j: ini4j 0.5.4
		paginatedadvancements: Paginated Advancements 2.4.2
		puzzle: Puzzle 1.6.0+1.20.2
			midnightlib: MidnightLib 1.5.0
			puzzle-base: Puzzle Base 1.6.0+1.20.2
			puzzle-gui: Puzzle GUI 1.6.0+1.20.2
			puzzle-models: Puzzle Models 1.6.0+1.20.2
			puzzle-splashscreen: Puzzle Splash Screen 1.6.0+1.20.2
		reeses-sodium-options: Reese's Sodium Options 1.7.0+mc1.20.2-build.97
		rrls: Remove Reloading Screen 3.2.2+mc1.20.2
		sodium: Sodium 0.5.3
		sodium-extra: Sodium Extra 0.5.3+mc1.20.2-build.114
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		viafabricplus: ViaFabricPlus 2.9.5
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20.2
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
		zoomify: Zoomify 2.12.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6

### Bug Description

Game crashes upon launch when ViaFabricPlus and NoChatReports are both enabled.

### Steps to Reproduce

1. Put ViaFabricPlus and NoChatReports in the mod folder
2. Attempt to launch the game
3. Game crashes

### Expected Behavior

Game will launch.

**Comment by FlorianMichael** [comment] 2023-11-27 12:46
What's the crash log / did you really tried out only installing the latest build and NCR?

**Comment by ManifestJW** [comment] 2023-11-27 15:57
[crash-2023-11-27_03.36.51-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/13477372/crash-2023-11-27_03.36.51-client.txt)

**Comment by FlorianMichael** [comment] 2023-11-27 15:59
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/298
Download the fix [here](https://github.com/ViaVersion/ViaFabricPlus/actions/runs/7005502372)

**Closed by FlorianMichael** 2023-11-27 15:59 UTC
Labels: bug
