### ISSUE TITLE
Failed to decode packet 'clientbound/minecraft:level_chunk_with_light' (MC <= 1.20.4)

### ISSUE THREAD

**Issue by 1zun4** [ViaVersion/ViaFabricPlus#413] opened 2024-05-13 10:07 UTC
### General Information

```
[12:01:57] [Render thread/INFO]: Connecting to hoplite.gg, 25565
[12:02:00] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:level_chunk_with_light'
[12:04:25] [Render thread/INFO]: Connecting to hoplite.gg, 25565
[12:04:28] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:level_chunk_with_light'
```

```
- minecraft 1.20.6
- viafabricplus 3.2.1
```

### Bug Description

Joining `hoplite.gg` with MC 1.20.1 results in the following error: `Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:level_chunk_with_light'`

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/12410754/ed32bec1-7971-4c4c-9f82-96abfb4e1e12)

### Steps to Reproduce

1. Select 1.20.1 on ViaFabricPlus
2. Join hoplite.gg

### Expected Behavior

You should be able to join the server. :)

**Comment by 1zun4** [comment] 2024-05-13 10:14
Happens also with Hypixel when selected 1.20.3-1.20.4.

**Comment by FlorianMichael** [comment] 2024-05-13 13:26
Duplicate of https://github.com/ViaVersion/ViaVersion/issues/3804

**Closed** 2024-05-14 16:53 UTC
Labels: bug
