### ISSUE TITLE
1.8.* - Book and Quills with text effects sometimes show the raw json .

### ISSUE THREAD

**Issue by ShadowShok** [ViaVersion/ViaFabricPlus#283] opened 2023-10-31 17:10 UTC
### General Information

I can't get it in a consistent way in a 1.8.9 server, however, on hypixel the issue happens on every book.

### Bug Description

Sometimes books with multiple text effects with interruptions will show sometimes some, or all the raw json of the book.

Example :
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/51331963/a089fe16-a1ac-4187-8786-92850f8e567b)

### Steps to Reproduce

Here's a picture of the book shown when i click on "The Delivery Man" in hypixel and then click on the disc named "Hytale Trailer"
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/51331963/a089fe16-a1ac-4187-8786-92850f8e567b)

### Expected Behavior

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/51331963/b5c8cf7d-adb1-4ea2-96c7-eaede8abc95e)

**Comment by FlorianMichael** [comment] 2023-11-02 07:50
Thanks for the bug report, however it's a duplicate of https://github.com/ViaVersion/ViaVersion/issues/3413

**Closed by FlorianMichael** 2023-11-02 07:50 UTC
Labels: bug
