### ISSUE TITLE
1.21.1 connecting to 1.21.3 server gives error.

### ISSUE THREAD

**Issue by oliik2013** [ViaVersion/ViaFabricPlus#611] opened 2024-11-09 18:08 UTC
### General Information

ViaVersion Dump: cant create gives error
latest.log: https://mclo.gs/4wQlm6x

### Bug Description

1.21.1 connecting to 1.21.3 server gives error
Error screenshot:
![image](https://github.com/user-attachments/assets/08c6551c-d504-4eea-a275-d962709ae16e)

### Steps to Reproduce

1. Have installed latest viafabricplus from modright on fabric 1.21.1
2. Have installed latest meteor client and baritrone from https://www.meteorclient.com/
3. Set the version to: 1.21.2-1.21.3
4. Join a 1.21.3 server (example: SurowySlimakOlka.aternos.me)
5. See the bug.

### Expected Behavior

I should not see the error and join the server normally.

**Comment by FlorianMichael** [comment] 2024-11-09 18:13
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/605

**Closed by FlorianMichael** 2024-11-09 18:13 UTC
Labels: bug

**Comment by oliik2013** [comment] 2024-11-10 20:00
btw someone joined the server from the issue (:    (username what joined: DevinLittle_  )
