### ISSUE TITLE
i getting when trying to join a 1.18.2 server: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/clientbound/minecraft:take_item_entity (class_2775) was larger than I expected, found 16 bytes extra whilst reading packet clientbound/minecraft:take_item_entity

### ISSUE THREAD

**Issue by RealHalapa** [ViaVersion/ViaFabricPlus#538] opened 2024-08-22 11:22 UTC
### what happening

the error is happening when i have to right on an item to join the server (server ip: play.woodcraft.hu) and if i right click i get the error "Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/clientbound/minecraft:take_item_entity (class_2775) was larger than I expected, found 16 bytes extra whilst reading packet clientbound/minecraft:take_item_entity" the protocol is set to 1.18.2

### Screenshots

here is a screenshot:
![Képernyőkép 2024-08-22 125309](https://github.com/user-attachments/assets/d295edc5-0580-4e64-9226-7371d974c65d)

### what give me the error

- joining to play.woodcraft.hu using 1.18.2
- loging into the server
- and right clicking with the nether star that should be send me to the server
- and its give me the error

### Expected Behavior

i should get to the server normaly and not get this error

### idk

i also see other people reporting this problem with different versions

**Comment by FlorianMichael** [comment] 2024-08-22 11:44
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/523

**Closed** 2024-08-22 11:44 UTC
Labels: bug
