### ISSUE TITLE
Crash on start state

### ISSUE THREAD

**Issue by Snaklilopin** [ViaVersion/ViaFabricPlus#291] opened 2023-11-19 13:40 UTC
### General Information

viafabricplus 2.9.5 , fabric-language-kotlin 1.10.13+kotlin.1.9.20 , fabric-api 0.90.7+1.20.2

### Bug Description

[tl-logger15462615712793351762.txt](https://github.com/ViaVersion/ViaFabricPlus/files/13403376/tl-logger15462615712793351762.txt)
[crash-2023-11-19_16.32.29-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/13403377/crash-2023-11-19_16.32.29-client.txt)

### Steps to Reproduce

Start mc(no more steps)

### Expected Behavior

I think this is happening due to a pirated client (It seems like it’s swearing at the users’ API, but I’m a tree and I don’t know if it’s true), maybe later I’ll log in from the official client

**Comment by FlorianMichael** [comment] 2023-11-19 16:27
This issue has already been fixed in the latest Dev build: https://github.com/ViaVersion/ViaFabricPlus/actions/runs/6914305698

**Closed by FlorianMichael** 2023-11-19 16:27 UTC
Labels: bug

**Comment by Snaklilopin** [comment] 2023-11-19 16:51
> This issue has already been fixed in the latest Dev build: https://github.com/ViaVersion/ViaFabricPlus/actions/runs/6914305698

Same problem
[tl-logger5270435886741483402.txt](https://github.com/ViaVersion/ViaFabricPlus/files/13403885/tl-logger5270435886741483402.txt)
[crash-2023-11-19_19.48.38-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/13403886/crash-2023-11-19_19.48.38-client.txt)

**Comment by FlorianMichael** [comment] 2023-11-19 17:03
I can't reproduce this issue using either the official Launcher, MultiMC or PrismLauncher, Piracy isn't supported anyways so please use a proper Launcher.
