### ISSUE TITLE
Cannot authentificate with bedrock

### ISSUE THREAD

**Issue by gegentan** [ViaVersion/ViaFabricPlus#229] opened 2023-08-24 18:46 UTC
### General Information

end of latest.log:

[20:34:07] [ForkJoinPool.commonPool-worker-137/INFO]: Getting device code for MSA login...
[20:34:07] [ForkJoinPool.commonPool-worker-137/INFO]: Got MSA device code, expires: 2023-08-24T20:49:07.543+02:00[Europe/Berlin]
[20:34:07] [ForkJoinPool.commonPool-worker-137/INFO]: Waiting for MSA login via device code...
[20:35:04] [ForkJoinPool.commonPool-worker-137/INFO]: Got MSA Code
[20:35:04] [ForkJoinPool.commonPool-worker-137/INFO]: Getting MSA Token...
[20:35:04] [ForkJoinPool.commonPool-worker-137/INFO]: Got MSA Token, expires: 2023-08-25T20:35:04.309+02:00[Europe/Berlin]
[20:35:04] [ForkJoinPool.commonPool-worker-137/INFO]: Authenticating device with Xbox Live...
[20:35:05] [ForkJoinPool.commonPool-worker-137/INFO]: Got XBL Device Token, expires: 2023-09-07T20:35:04.648+02:00[Europe/Berlin]
[20:35:05] [ForkJoinPool.commonPool-worker-137/INFO]: Authenticating with Xbox Live using SISU...
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: Got XBL Title+User+XSTS Token, expires: 2023-08-25T00:35:05.625+02:00[Europe/Berlin]
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: Authenticating with Minecraft Services...
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: io.jsonwebtoken.security.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:399)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:529)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:589)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at io.jsonwebtoken.impl.ImmutableJwtParser.parseClaimsJws(ImmutableJwtParser.java:173)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.bedrock.StepMCChain.applyStep(StepMCChain.java:89)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.bedrock.StepMCChain.applyStep(StepMCChain.java:48)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at de.florianmichael.viafabricplus.base.settings.groups.BedrockSettings.lambda$new$8(BedrockSettings.java:51)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[20:35:06] [ForkJoinPool.commonPool-worker-137/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

### Bug Description

Error message in minecraft says to look in the latest.log file

### Steps to Reproduce

In viafabricplus settings click authenticate bedrock account

### Expected Behavior

should authenticate

**Comment by FlorianMichael** [comment] 2023-08-24 19:08
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/228, already fixed

**Closed by FlorianMichael** 2023-08-24 19:08 UTC
Labels: bug

**Comment by FlorianMichael** [comment] 2023-08-24 19:24
v2.8.5 should have fixed the issue now
