### ISSUE TITLE
Support for Betacraft Heartbeat

### ISSUE THREAD

**Issue by alfonsojon** [ViaVersion/ViaFabricPlus#555] opened 2024-09-11 05:14 UTC
### Problem Description

Currently, old versions do not show server details due to not supporting server ping. The Betacraft launcher has addressed this issue by [introducing a heartbeat utility](https://betacraft.uk/heartbeat-tutorial) that supports a very large range of Minecraft server versions, all the way from classic to modern Minecraft. 

![image](https://github.com/user-attachments/assets/90ac1f01-885e-415a-805e-869e713c60e7)

### Solution Description

This [heartbeat utility](https://betacraft.uk/heartbeat-tutorial) could be used by ViaFabricPlus as a "server ping" for versions of Minecraft server that do not natively ping, potentially adding some server details for old Minecraft servers to modern Minecraft's server list.

![image](https://github.com/user-attachments/assets/7a66cbcc-381e-4f78-bc9b-054d432b3bc1)

### Alternatives

Have not researched other ping options

### Additional Info

https://betacraft.uk/heartbeat-tutorial

**Comment by christopherplaysminecraft** [comment] 2024-09-11 22:16
https://discord.com/channels/316206679014244363/1112835241271373966/1283521678386925668
https://discord.com/channels/316206679014244363/1112835241271373966/1283522488931844167

**Comment by FlorianMichael** [comment] 2024-09-25 15:50
As far as I know the heartbeat functionality is only used by servers to add themselves to the BetaCraft server list (which already is implemented in ViaFabricPlus).

I am unsure how we could use this for pinging specific servers (as it would require to always have the betacraft server list loaded / wouldn't work on most servers.

**Comment by FlorianMichael** [comment] 2024-09-25 22:41
I asked on their Discord and they confirmed that it's only for servers, closing the issue since I don't see how we could implement pinging

**Closed by FlorianMichael** 2024-09-25 22:41 UTC
Labels: enhancement
