### ISSUE TITLE
Container Close causes a disconnect on 1.8.X

### ISSUE THREAD

**Issue by ModdingPink** [ViaVersion/ViaFabricPlus#658] opened 2024-12-21 02:33 UTC
### General Information

Found as game servers which use a GUI to transport players between internal servers causes a disconnect when the container is closed, making you unable to join said game.

### Bug Description

Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packed play/clientbound/minecraft:container_close
[latest.log](https://github.com/user-attachments/files/18216919/latest.log)

### Steps to Reproduce

Join hypixel.net with version set to 1.8
Enter the Bedwars Lobby
Click on one of the gamemode players
Click the "Practice" wool in the bottom left corner
Select any of the options

### Expected Behavior

Servers closing containers shouldn't cause a connection error

**Comment by lowercasebtw** [comment] 2024-12-21 02:56
Duplicate of https://github.com/ViaVersion/ViaVersion/issues/4308

**Closed** 2024-12-21 02:56 UTC
Labels: bug
