### ISSUE TITLE
Incompatible with memory leak fix (1.19.4)

### ISSUE THREAD

**Issue by OstapOmega** [ViaVersion/ViaFabricPlus#174] opened 2023-07-08 20:03 UTC
### General Information

Sodium, Viafabricplus, Memory leak fix and very many optimization mods

### Bug Description

game crashing with this mod 
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/67763024/8e3622fb-2131-429e-b578-4206a81d074e)

### Steps to Reproduce

1. Install memory leak fix with viafabricplus
2. see the game crashing

### Expected Behavior

the game should launch

**Comment by allinkdev** [comment] 2023-07-08 20:04
Duplicate of #103

**Closed** 2023-07-08 20:12 UTC
Labels: bug
