### ISSUE TITLE
ViaFabricPlus is incompatible with Feather Client 1.21.3

### ISSUE THREAD

**Issue by Aqxorus** [ViaVersion/ViaFabricPlus#662] opened 2024-12-24 02:25 UTC
### General Information

Crash report url: https://mclo.gs/6RqpTMm

### Bug Description

Starting game causes game to crash.

### Steps to Reproduce

1. Enable ViaFabricPlus for Feather Client 1.21.3
2. Game crashes

### Expected Behavior

The game shouldn't crash when ViaFabricPlus is enabled.

**Comment by Kichura** [comment] 2024-12-24 02:44
Duplicate of #157 but the tl;dr: won't be fixed.

**Closed by Kichura** 2024-12-24 02:44 UTC
Labels: bug
