### ISSUE TITLE
The mod conflicts

### ISSUE THREAD

**Issue by largenton** [ViaVersion/ViaFabricPlus#155] opened 2023-06-25 10:36 UTC
### General Information

The mod conflicts with the mod on version 1.20.1 quilt 0.19.2.beta.2

### Bug Description

Unhandled solver error involving the following rules:
Rule 1:
Mandatory mod Memory Leak Fix (memoryleakfix) v1.1.1
Rule 2:
Mandatory mod ViaFabricPlus (viafabricplus) v2.7.7
Rule 3:
Breakage for {org.quiltmc.loader.impl.plugin.fabric.FabricModOption 'viafabricplus' from <mods>/viafabricplus-2.7.7.jar} on memoryleakfix versions [*] (1 breaking options, 0 okay options)
	x {org.quiltmc.loader.impl.plugin.fabric.FabricModOption 'memoryleakfix' from <mods>/memoryleakfix-fabric-1.17+-1.1.1.jar} {org.quiltmc.loader.impl.plugin.fabric.FabricModOption 'memoryleakfix' from <mods>/memoryleakfix-fabric-1.17+-1.1.1.jar}

### Steps to Reproduce

Run the mod along with Memory Leak Fix

### Expected Behavior

Crush

**Comment by allinkdev** [comment] 2023-06-25 10:39
Duplicate of #103

**Closed** 2023-06-25 10:41 UTC
Labels: bug
