### ISSUE TITLE
Hypixel/Minemen status

### ISSUE THREAD

**Issue by CamperSamu** [ViaVersion/ViaFabricPlus#13] opened 2023-03-19 01:42 UTC
Is this mod safe in any way with strict anticheat servers?
From playing the 1.8 pvp feels very faithful but idk how much is replicated about 1.8 to avoid false bans.

**Comment by FlorianMichael** [comment] 2023-03-19 12:23
The goal of ViaFabricPlus is that you are not banned, it is specially coded for that.

**Comment by SzczurekYT** [comment] 2023-06-09 13:50
Well, I just got banned from minemen.club in 1.7 mode, while playing some sumos.
No issue, I don't play there, but just leaving a note, that's still there's something that flagged the anticheat.

**Comment by FlorianMichael** [comment] 2023-06-09 13:51
I did never test 1.7 PVP, only 1.8 PVP

**Comment by Kichura** [comment] 2023-06-09 13:52
Yeah this has been an issue in multiconnect and viafabric *(non-plus variant)* themselves too, although contacting minemen just results in them being rude to us all again.

**Comment by SzczurekYT** [comment] 2023-06-09 14:01
> I did never test 1.7 PVP, only 1.8 PVP

I'm not sure on the differences, but the 1.8 works very well, with me not getting banned on any server I tried, including hypixel.

**Comment by Felix14-v2** [comment] 2023-06-10 08:27
> there's something that flagged the anticheat

Keep in mind that you can still be banned even without VFP if the anti-cheat is poorly configured :)
Replay recording would be helpful, but ViaFabricPlus no longer compatible with it since 2.7.3.

**Comment by Nixuge** [comment] 2023-06-12 18:46
> Keep in mind that you can still be banned even without VFP if the anti-cheat is poorly configured :)
MMC's anticheat is really angry at anything that's even just a bit different from vanilla 1.7.10/1.8.9 mechanics (eg iirc some 1.8.3 specific movement was false banning at some point), but over the years it's gotten consistent at pretty much eliminating falsebans 
Not saying it's 100% VFP's fault, but there's a REALLY high chance that it is

**Comment by SzczurekYT** [comment] 2023-06-13 08:15
Yesterday I got banned on hypixel too for 30 days, for cheating, unfair adventage (I didn't cheat). 😐
I the moment I got banned I was afk on skyblock doing something else, then I alt-tabbed to minecraft just to see that I'm banned. 
On 1.8.9 mode.
I thought about appeling, but I don't think they will accept it as in [allowed mods](https://hypixel.net/allowed-mods) section I found this:
> Finally, modifications that alter the way in which your Minecraft client interacts with and communicates with our server are also strictly disallowed, even if they otherwise fall into an allowed category. Please ensure that any modifications which are used are strictly client-side only, with them not changing or altering the behavior of the game.

So I doubt if they are interested in allowi g / supporting client side shenenigans.

Lesson: Overall the 1.8 mode work pretty well, but still there's risk that you will get banned on more strict servers like hypixel, minemen, pvp.land (In one fight with friend I got kicked for sus behavior).

There is a room for improvment, and it makes sense that it's hard to magically turn 1.19 into 1.8.9, perfectly remaking all the mechanics.

**Comment by TheKodeToad** [comment] 2023-06-17 13:00
For science :tm: i joined minemen in 1.7. and yep i got banned before even playing! Just from opening a menu by right clicking with a sword a few times.

**Comment by FlorianMichael** [comment] 2023-06-17 15:55
> For science ™️ i joined minemen in 1.7. and yep i got banned before even playing! Just from opening a menu by right clicking with a sword a few times.

Yeah, 1.7 PVP is absolutely not built into VFP, with the 1.8 this should not happen, never tested the 1.7 on Minemen / with VFP, but I know of many things that I would still have to fix

**Comment by SzczurekYT** [comment] 2023-06-18 17:39
I think it would be better to focus on 1.8 first, as while it works very well now, but it's still flagging on stricter servers.
From what I played:
Hypixel - Took pretty long but at some point I got banned.
pvp.land - Got kicked for suspicious behaviour during fight, didn't use it more to avoid a ban.
Othere servers where I played were antiac.net - no issues and bedwarspractice.club - no issues too, only got kicked once for not responding to keep alive packes, but that could be unrelated to VFP.

**Comment by FlorianMichael** [comment] 2023-06-18 17:43
Thanks for your help @SzczurekYT  I will reopen this issue since it's still a topic

**Comment by Appolon24800** [comment] 2023-08-26 20:05
I get insta ban (I think its the blocking)
I get unban after btw

www.youtube.com/watch?v=8RnpTcc_fhE

**Comment by SzczurekYT** [comment] 2023-08-27 07:31
It's nice that at least they gave you an unban.
I think it would be good to add some kind of warning, so people don't get banned.
One would be when you enable 1.7.x since it's not tested, and another one when joining strict servers (like hypixel, minemen, a list could be created) with 1.8.x, informing that while 1.8 translation is pretty good it's still not perfect and there were known bans on this server previously.

**Comment by FlorianMichael** [comment] 2023-08-27 08:00
> 

You are using the 1.19.4 version of ViaFabricPlus which isn't supported anymore, but yeah, the ban reason / the way you triggerd the ban is already known and will be fixed in the future, I think it's already on the TODO list

**Comment by Player005** [comment] 2023-10-12 10:05
@FlorianMichael any updates on this? The blocking sword while in inventory bug is I think the bug causing the most anticheat false bans, would be really nice to see that fixed

**Comment by FlorianMichael** [comment] 2023-10-12 16:24
@Player005 No not at the moment, I'll see when I generally make more improvements to the whole 1.9 -> 1.8 protocol, there are some more things that need to be fixed in the main project (ViaVersion) as well. But don't worry, the issues on the bug tracker are not forgotten, it's just always very time consuming and a lot of work to fix them.

**Comment by FlorianMichael** [comment] 2023-11-27 13:20
PvP and Block placing issues should now be fixed / better in ViaFabricPlus 3, you can download the test version of 3.0.0 [here](https://github.com/ViaVersion/ViaFabricPlus/actions/runs/7005570403), don't be surprised it is still displayed in game as 2.9.9-SNAPSHOT. I would appreciate if some of you could give some feedback so we can move on with this issue.

**Comment by FlorianMichael** [comment] 2023-11-28 18:44
After some testing I was able to find out that the issues should be fixed in 3.0.0 so I'm going to close this issue for now, if anyone comes up with new information I'll reopen it.

**Closed by FlorianMichael** 2023-11-28 18:44 UTC
Labels: good first issue, question, v3

**Comment by SzczurekYT** [comment] 2023-12-02 11:27
> PvP and Block placing issues should now be fixed / better in ViaFabricPlus 3, you can download the test version of 3.0.0 [here](https://github.com/ViaVersion/ViaFabricPlus/actions/runs/7005570403), don't be surprised it is still displayed in game as 2.9.9-SNAPSHOT. I would appreciate if some of you could give some feedback so we can move on with this issue.

Yeah, placing blocks inside player is fixed.

But still got instabanned on minenmen just after 3 rightclicks 😆
I'm not gonna try hypixel as I had one ban in the summer and I don't want to make the situation look worse.
If you have any other servers to try on I can do that.

**Comment by Player005** [comment] 2023-12-02 13:14
After testing the latest GH actions build on both hypixel and pvp.land for over an hour, it's working pretty well so far, I have not been banned on either server (I only got kicked by the anticheat for "suspicious behavior" two times on pvp.land, but that sometimes also happens when playing normal 1.8). 
However, I noticed that sword blocking now only works when aiming at a block and not when looking in the air. This can be observed on `pvpgym.net` in the practice lobby or in the arena mode on `pvp.land` - on these servers, right-clicking the sword only opens the GUI when looking on the ground, when using 1.8 or the release version of VFP it always works even when looking in the sky.
Also, on these servers you can see that when holding down right-click on the sword and the GUI opens, the sword will remain blocked in the background even tho there is an open inventory. This was, however, already an issue in earlier VFP versions and is not caused by this update.
Anyway, thank you very much for your work on this mod, it finally makes playing hypixel on 1.20 somewhat enjoyable!

**Comment by FlorianMichael** [comment] 2023-12-02 13:19
@SzczurekYT Placing blocks inside the player was already fixed in v2 versions and I don't get banned anymore on minemen, weird, do you maybe have some other mods installed which are changing pvp?

**Comment by SzczurekYT** [comment] 2023-12-02 14:07
> After testing the latest GH actions build on both hypixel and pvp.land for over an hour, it's working pretty well so far, I have not been banned on either server

Don't be too confident yet, they may not ban you instantly. For example when I got banned I was standing afk on skyblock.

> [...] I don't get banned anymore on minemen, weird, do you maybe have some other mods installed which are changing pvp?

I have many mods installed so it's possible, but I don't have any in my mind that could affects this.
I should probably make a clean instance with performance mods and VFP only.

**Comment by FlorianMichael** [comment] 2023-12-02 14:25
@SzczurekYT Yeah please do that as I can't reproduce those bans anymore.

**Comment by 0-x-2-2** [comment] 2023-12-23 07:41
I've played for >40 hours on MMC without issues with the 1.20.4 version. Seems like 1.8 still flags on much stricter anti-cheats that can detect <100% Keep Sprint better such as Grim.

![Screenshot from 2023-12-23 02-40-45](https://github.com/ViaVersion/ViaFabricPlus/assets/9968651/634e349c-41de-4b3f-8b2a-78478bd871c4)

![Screenshot from 2023-12-23 02-41-28](https://github.com/ViaVersion/ViaFabricPlus/assets/9968651/0b7d4c9b-92b9-4bce-a5de-64fe5a97074d)

**Comment by SouravPrakash5** [comment] 2024-01-23 07:21
I am Confused That I should use this for 1.8 on minemen and hypixel or not

**Comment by Player005** [comment] 2024-01-23 08:01
@SouravPrakash5 you can, and most likely you won't get banned, however  there is of course a small risk that you do get banned, so it's up to you if you wanna take that risk.

**Comment by christopherplaysminecraft** [comment] 2024-01-23 11:58
I have more than 250 hours of playtime on Hypixel with ViaFabricPlus 3 and I have never been banned or even kicked, so I would say it's pretty safe

**Comment by Felix14-v2** [comment] 2024-01-25 14:32
You can also use ReplayMod to prove your legitimacy

**Comment by christopherplaysminecraft** [comment] 2024-01-25 15:29
I don't think Hypixel unbans people just because they can provide video material/replays.

Hypixel literally has their own replay system `/replay`
So I don't think having your own material would change any of that

**Comment by LittleChest** [comment] 2024-03-16 17:33
I just got banned, seemingly for inexplicable lag when joining a 1.8 server using a 1.20.4 client.

**Comment by FlorianMichael** [comment] 2024-03-16 18:24
Which server?

**Comment by LittleChest** [comment] 2024-03-17 03:38
> Which server?

Clover Pixel uses their own anti-cheat

**Comment by SzczurekYT** [comment] 2024-03-17 07:54
It might be because of the internet connection, one time I got banned on some server while playing on lunar client (1.8.9) by an anticheat, because suddenly my internet disconnected / started lagging for a moment.
The admin checked my logs, we saw a lot of timeouts there and he unbanned me.
In a situation like this it's hard to tell, what failed, and whose fault is this.

**Comment by LittleChest** [comment] 2024-03-17 09:11
> It might be because of the internet connection, one time I got banned on some server while playing on lunar client (1.8.9) by an anticheat, because suddenly my internet disconnected / started lagging for a moment. The admin checked my logs, we saw a lot of timeouts there and he unbanned me. In a situation like this it's hard to tell, what failed, and whose fault is this.

No, I opened the Ping debug table and continued the game, after the window suddenly became unresponsive I checked the table and there was no network lag. And the sudden unresponsiveness of the window indicates that the problem is not with the network.

**Comment by NoboKik** [comment] 2024-11-10 08:35
Got banned twice on minemen on the newest version of ViaFabricPlus on 1.21, however it worked fine on 1.20.4

**Comment by Delationnn** [comment] 2025-03-29 12:45
I have gotten banned when playing Minemen on 1.21.4 translating to 1.8, please beware!

**Comment by CarPBon** [comment] 2025-07-13 19:32
I'm pretty sure Minemen warns against using Debugify in their Modern Practice servers, I got banned (had to make a ticket to get unbanned) and remembered that I had Debugify installed. Just to be on the safe side, don't install Debugify!

**Comment by john482847573** [comment] 2026-05-23 12:11
i got banned from minemen with viafabricplus set to 1.7.10 on 26.1

**Comment by florianreuth** [comment] 2026-05-23 12:14
It would be better to open a new issue since this one has been closed for a while now.
