### ISSUE TITLE
error with hypixel 1.8.x

### ISSUE THREAD

**Issue by Piezku** [ViaVersion/ViaFabricPlus#201] opened 2023-07-28 14:01 UTC
### General Information

<img width="1672" alt="Sieppaa" src="https://github.com/ViaVersion/ViaFabricPlus/assets/137830834/a05091ba-d298-44e9-bcb5-32447ac5a2cd">
this error comes sometimes when playing on hypixel with 1.8.x selected. (i have newest version of viafabricplus, fabric and fabric api installed)

### Bug Description

joining hypixel with 1.8.x causes the error

### Steps to Reproduce

join hypixel with 1.8.x and after playing farm hunt some levels cause kick with this error

### Expected Behavior

not sure what to say here

**Comment by FlorianMichael** [comment] 2023-08-01 02:16
And what's the actual error?

**Comment by Piezku** [comment] 2023-08-01 03:12
[06:06:50] [Netty Client IO #11/ERROR]: An error occurred in metadata handler MetadataRewriter1_9To1_8 for TIPPED_ARROW entity type: Metadata{id=10, metaType=Byte, value=2}
[06:06:50] [Netty Client IO #11/ERROR]: Full metadata: Metadata{id=0, metaType=Byte, value=32}
Metadata{id=1, metaType=Short, value=300}
Metadata{id=2, metaType=String, value=KCcooldude11's poop}
Metadata{id=3, metaType=Byte, value=1}
Metadata{id=4, metaType=Byte, value=1}
Metadata{id=6, metaType=Float, value=20.0}
Metadata{id=7, metaType=Int, value=0}
Metadata{id=8, metaType=Byte, value=0}
Metadata{id=9, metaType=Byte, value=0}
Metadata{id=10, metaType=Byte, value=2}
Metadata{id=11, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@649bf476}
Metadata{id=12, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@3f1cec0c}
Metadata{id=13, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@117f95d}
Metadata{id=14, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@2407f710}
Metadata{id=15, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@1f849fa2}
Metadata{id=16, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@47a06cd2}
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: java.lang.Exception: Could not find valid metadata
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocols.protocol1_9to1_8.metadata.MetadataRewriter1_9To1_8.handleMetadata(MetadataRewriter1_9To1_8.java:46)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.callOldMetaHandler(EntityRewriter.java:155)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:110)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocols.protocol1_9to1_8.storage.EntityTracker1_9.sendMetadataBuffer(EntityTracker1_9.java:350)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.SpawnPackets$2.lambda$register$1(SpawnPackets.java:69)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:45)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:30)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at net.raphimc.vialoader.netty.ViaDecoder.channelRead(ViaDecoder.java:56)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[06:06:50] [Netty Client IO #11/ERROR]: An error occurred in metadata handler MetadataRewriter1_9To1_8 for TIPPED_ARROW entity type: Metadata{id=12, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@3f1cec0c}
[06:06:50] [Netty Client IO #11/ERROR]: Full metadata: Metadata{id=0, metaType=Byte, value=32}
Metadata{id=1, metaType=Short, value=300}
Metadata{id=2, metaType=String, value=KCcooldude11's poop}
Metadata{id=3, metaType=Byte, value=1}
Metadata{id=4, metaType=Byte, value=1}
Metadata{id=6, metaType=Float, value=20.0}
Metadata{id=7, metaType=Int, value=0}
Metadata{id=8, metaType=Byte, value=0}
Metadata{id=9, metaType=Byte, value=0}
Metadata{id=11, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@649bf476}
Metadata{id=12, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@3f1cec0c}
Metadata{id=13, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@117f95d}
Metadata{id=14, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@2407f710}
Metadata{id=15, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@1f849fa2}
Metadata{id=16, metaType=Rotation, value=com.viaversion.viaversion.api.minecraft.EulerAngle@47a06cd2}
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: java.lang.Exception: Could not find valid metadata
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocols.protocol1_9to1_8.metadata.MetadataRewriter1_9To1_8.handleMetadata(MetadataRewriter1_9To1_8.java:46)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.callOldMetaHandler(EntityRewriter.java:155)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:110)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocols.protocol1_9to1_8.storage.EntityTracker1_9.sendMetadataBuffer(EntityTracker1_9.java:350)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.SpawnPackets$2.lambda$register$1(SpawnPackets.java:69)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:45)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:30)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at net.raphimc.vialoader.netty.ViaDecoder.channelRead(ViaDecoder.java:56)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[06:06:50] [Netty Client IO #11/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SPAWN_ENTITY (0x0E)
[06:06:50] [Netty Client IO #11/ERROR]: An error occurred in metadata handler EntityPackets for untracked entity type: Metadata{id=6, metaType=MetaType{typeId=0, type=Byte}, value=0}
[06:06:50] [Netty Client IO #11/ERROR]: Full metadata: Metadata{id=0, metaType=MetaType{typeId=0, type=Byte}, value=0}
Metadata{id=1, metaType=MetaType{typeId=1, type=VarInt}, value=300}
Metadata{id=2, metaType=MetaType{typeId=5, type=JsonElement}, value=null}
Metadata{id=3, metaType=MetaType{typeId=7, type=Boolean}, value=false}
Metadata{id=4, metaType=MetaType{typeId=7, type=Boolean}, value=false}
Metadata{id=6, metaType=MetaType{typeId=0, type=Byte}, value=0}
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: java.lang.ClassCastException: class java.lang.Byte cannot be cast to class java.lang.Integer (java.lang.Byte and java.lang.Integer are in module java.base of loader 'bootstrap')
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocols.protocol1_19_3to1_19_1.packets.EntityPackets.lambda$registerRewrites$2(EntityPackets.java:162)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:126)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter$4.lambda$register$0(EntityRewriter.java:388)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:45)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:30)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at net.raphimc.vialoader.netty.ViaDecoder.channelRead(ViaDecoder.java:56)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:06:50] [Netty Client IO #11/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Piezku** [comment] 2023-08-01 03:13
there is the whole error, i did not put the whole log file because its many megabytes large

**Comment by FlorianMichael** [comment] 2023-08-04 20:15
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/149

**Closed by FlorianMichael** 2023-08-04 20:15 UTC
Labels: bug

**Comment by Piezku** [comment] 2023-09-01 01:05
When will this be fixed
