### ISSUE TITLE
Follow up on #608

### ISSUE THREAD

**Issue by Ma110w** [ViaVersion/ViaFabricPlus#610] opened 2024-11-06 04:43 UTC
### General Information

I generated several log's just to see if anything changed between them when doing different things.
(they are in hieratical order, so 1 was generated first)

[faillog1 (should be same as faillog2).txt](https://github.com/user-attachments/files/17641698/faillog1.should.be.same.as.faillog2.txt)
[faillog2.txt](https://github.com/user-attachments/files/17641699/faillog2.txt)
[faillog3(didnt accept resource pack).txt](https://github.com/user-attachments/files/17641701/faillog3.didnt.accept.resource.pack.txt)
[faillog4(paired with multimclog).txt](https://github.com/user-attachments/files/17641702/faillog4.paired.with.multimclog.txt)
[multimclog.txt](https://github.com/user-attachments/files/17641703/multimclog.txt)

### Bug Description

Joining a realm with Bedrock ~Mods~ "Add-Ons" installed causes complete failure

_io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: net.raphimc.viabedrock.api.protocol.StatelessTransitionProtocol$$Lambda/0x00000174823173f0_

### Steps to Reproduce

Attempt to join a bedrock realm on latest with "Add-Ons"

### Expected Behavior

The error could shouldn't be displayed, and i shouldn't be writing this github issue rn

**Comment by RaphiMC** [comment] 2024-11-06 15:54
Your issue description is lacking a lot of information regarding the steps to reproduce the issue. Easiest option would be to provide a public server / realm invite where this can be tested

**Comment by Ma110w** [comment] 2024-11-08 22:32
So heres a realm invite https://realms.gg/9dUg5VcXafgUSsA i found out that joining a bedrock realm works, joining a modded bedrock realm will result in a state where you are completely unable to interact with any inventory related blocks or things, including console commands, and joining a modded bedrock realm WITH modded items in your inventory result in the error

**Comment by RaphiMC** [comment] 2024-11-10 23:05
> So heres a realm invite https://realms.gg/9dUg5VcXafgUSsA i found out that joining a bedrock realm works, joining a modded bedrock realm will result in a state where you are completely unable to interact with any inventory related blocks or things, including console commands, and joining a modded bedrock realm WITH modded items in your inventory result in the error

Thanks. Interacting with inventories is currently not implemented, so its expected to not work. Commands however should work. Can you provide steps on how I can obtain the modded item which causes the error

**Comment by Ma110w** [comment] 2024-11-11 09:26
@RaphiMC i see you haven't joined yet

**Comment by Ma110w** [comment] 2024-11-11 09:30
@RaphiMC  you have operator in that realm, but i will place some modded items in a near by chunk, or you can use mc bedrock to give yourself one, or we can schedule a time to do this

**Comment by RaphiMC** [comment] 2024-11-11 18:32
I had no issues connecting to the realm with ViaBedrock (Using the latest ViaProxy dev build)
![image](https://github.com/user-attachments/assets/4699b473-0499-4bc7-b55d-3c9d1c5f610b)

Try redownloading the latest ViaFabricPlus dev build. Maybe one of the mods you have installed is interfering

**Comment by FlorianMichael** [comment] 2024-11-16 00:52
Closing as cannot reproduce, if you have anything to add we'll reopen the issue

**Closed by FlorianMichael** 2024-11-16 00:52 UTC
Labels: bug
