### ISSUE TITLE
Kick

### ISSUE THREAD

**Issue by Pan4ur** [ViaVersion/ViaFabricPlus#308] opened 2023-12-08 16:55 UTC
### General Information

ViaFabric+ 3.0.0 1.20.4 with latest Fabric API and latest Fabric Loader

### Bug Description

Kick
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/82473048/f335c211-48b7-46bc-bc8b-c0ed59537e41)

### Steps to Reproduce

1. Select 1.20.1
2. Connect to crystalpvp.cc
3. Wait for a server message

### Expected Behavior

So I don't get kicked out

**Comment by FlorianMichael** [comment] 2023-12-09 01:38
I can't reproduce this issue using a clean Minecraft 1.20.4 client, try to uninstall mods

**Comment by Pan4ur** [comment] 2023-12-09 05:33
https://youtu.be/BD_2PdCsryE

**Comment by PrimePranay7** [comment] 2023-12-09 14:22
I am getting the game error plz help
![Screenshot 2023-12-09 165648](https://github.com/ViaVersion/ViaFabricPlus/assets/86054367/dcc94a06-6e78-4717-879f-032b2e247229)

**Comment by ancap-kun** [comment] 2023-12-09 14:31
The issue is 100% valid, i have same on clean client with fabric api 0.91.2 and viafabricplus on 0.15.1 loader. On server mentioned above (crystalpvp.cc) it happens in 5-10 seconds after joining.

**Comment by FlorianMichael** [comment] 2023-12-09 14:32
Yeah I could also reproduce it now

**Comment by FlorianMichael** [comment] 2023-12-10 20:53
This issue is fixed in the dev version, you can download it here: https://github.com/ViaVersion/ViaFabricPlus/actions/runs/7158875283

**Closed by FlorianMichael** 2023-12-10 20:53 UTC
Labels: bug
