### ISSUE TITLE
Fishing Rod Inaccuracy

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaFabricPlus#504] opened 2024-08-05 15:08 UTC
### General Information

none

### Bug Description

On version 1.8.x, when using the rod, your arm is supposed to swing when using it.

There also seems to be a delay when using the rod

### Steps to Reproduce

Join a 1.8.x server
Use a fishing rod

### Expected Behavior

Arm is supposed to swing on use and on retract

**Comment by FlorianMichael** [comment] 2024-08-07 11:21
Duplicate of https://github.com/ViaVersion/ViaVersion/issues/3762

**Comment by lowercasebtw** [comment] 2024-08-09 04:33
https://github.com/ViaVersion/ViaFabricPlus/blob/3435928fb78debcdfd88d4969a22caebf7a2010a/src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/MixinMinecraftClient.java#L95

This is where the fishing rod punch issue is happening, as it is checking for 1.15+ it denies any swinging of items prior to 1.15 but fishing rods use to swing prior to 1.15

**Comment by lowercasebtw** [comment] 2024-08-10 00:13
Imo, the fix would be to remove the two uses of disableSwing & disableSwing2 in MixinMinecraftClient & instead, mixin into the items that call the swing method like Snowball, egg, etc and redirect the use there

**Comment by lowercasebtw** [comment] 2024-08-10 00:22
Btw the code was a guess from a friend, and after testing doesn't seem to be the culprit of the issue

Looking further into it

**Closed** 2024-08-15 06:47 UTC
Labels: bug
