### ISSUE TITLE
Cannot Blip Jump in pre-1.9

### ISSUE THREAD

**Issue by ManInMyVan** [ViaVersion/ViaFabricPlus#225] opened 2023-08-22 00:06 UTC
### General Information

|Mod|Version|
|:-:|:-:|
Minecraft | 1.20.1
Fabric | 0.14.21
ViaFabricPlus | 2.8.2
Fabric API | 0.87.0
ModMenu | 7.2.1
Sodium | 0.5.2
Sodium Extra | 0.5.1
Reeses Sodium Options | 1.6.4
Indium | 1.0.25
ImmediatelyFast | 1.1.28
MoreCulling | 0.19.0
Starlight | 1.1.2
Ksyxis | 1.1
EntityCulling | 1.6.2
Dashloader | 5.0.0 beta 2
Gamma Utils | 1.7.16
Debugify | 2.0
Continuity | 3.0.0 beta 3
NoChatReports | 2.2.2
Tweakeroo | 0.17.1
MaliLib | 0.16.1
3dSkinLayers | 1.5.4
SheepConsistency | 1.0.4
Essential
OpenMCSkins | 2.0.3
Symbol Chat | 1.1.2
NBTac | 1.1.4
NBTEditor | 1.12.1
Cloth Config | 11.1.106
Yet Another Config Lib | 3.1.0
Meteor Client | 0.5.4 #1913
Meteor Rejects | 0.3
SeedCrackerX | 2.14.4
Server Seeker | 2.1.0
ClientCommands | 2.8.3
Marlows Crystal Optimizer | 1.19.X

### Bug Description

I cannot blip jump in pre-1.9 (I'm using 1.8.9)

### Steps to Reproduce

You probably already know what a blip is, but, [here's a wiki page on it](https://www.mcpk.wiki/wiki/Blip) and [here's some tutorials](https://google.com/search?q=how+to+do+a+blip+jump&tbm=vid).

### Expected Behavior

I should be able to blip jump

**Comment by Blayung** [comment] 2023-08-22 09:56
Skill issue

**Comment by FlorianMichael** [comment] 2023-08-23 01:31
I will look into that as soon as I am home

**Comment by FlorianMichael** [comment] 2023-08-24 15:19
Can you please try to remove all your installed mods except the fabric api and viafabricplus?

**Comment by ManInMyVan** [comment] 2023-08-25 18:12
Still can't

**Comment by lowercasebtw** [comment] 2024-08-10 22:49
Any update?

**Comment by FlorianMichael** [comment] 2024-08-10 22:49
It's still a TODO as the issue is still open

**Comment by lowercasebtw** [comment] 2024-08-28 20:34
whats a blip jump

**Comment by FlorianMichael** [comment] 2024-08-28 20:34
Looks at "Steps to reproduce"

**Comment by lowercasebtw** [comment] 2024-11-27 20:05
Working on a fix, should be fixed soon.

**Comment by FlorianMichael** [comment] 2024-11-29 15:03
Should be fixed in dev builds now, thanks for reporting

**Closed** 2024-11-29 15:03 UTC
Labels: bug
