### ISSUE TITLE
Incompatible with Puzzle's lib

### ISSUE THREAD

**Issue by viktordimov** [ViaVersion/ViaFabricPlus#372] opened 2024-03-01 13:40 UTC
### General Information

I can't launch the client with ViaFabricPlus enabled

### Bug Description

It seems to have some kind of compatibility issue with Puzzle's Lib (reported to them as well)

### Steps to Reproduce

Install any Fuzs's mod alongside ViaFabricPlus
Try to launch the game
No crash reports, only a halt and an erros in the [log ](https://pastebin.com/TJU6YD8i)

### Expected Behavior

No conflict.

**Comment by FlorianMichael** [comment] 2024-03-01 18:19
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/356

**Closed by FlorianMichael** 2024-03-01 18:19 UTC
Labels: bug
