### ISSUE TITLE
Can't Join Server with Simple Voice Chat

### ISSUE THREAD

**Issue by DreiPixel** [ViaVersion/ViaFabricPlus#532] opened 2024-08-18 23:04 UTC
### General Information

ViaVersion dump: https://dump.viaversion.com/4f41380712cb9074ac5e9e86bc8277822b96bbf7431fafb366c1d545e64bd341

### Bug Description

Joining a Server with SimpleVoiceChat (having it both on Client and Server) Results in a Decoder Exception.
Client is 1.21 and Server is 1.20.4
[disconnect-2024-08-19_00.57.34-client.txt](https://github.com/user-attachments/files/16652869/disconnect-2024-08-19_00.57.34-client.txt)

### Steps to Reproduce

1. Have ViaFabricPlus and Simple Voice Chat installed (Client and Server)
2. Try to Join Server
3. Error

### Expected Behavior

Not having that error and join the server WITH Simple Voice Chat.

**Comment by FlorianMichael** [comment] 2024-08-19 00:28
Joining modded servers accross different versions is generally not supported; The issue is most likely SimpleVoiceChat having a different network protocol in 1.20.4 then in 1.21 which ViaFabricPlus doesn't support/rewrite.

**Comment by Gaming32** [comment] 2024-08-19 00:35
Simple Voice Chat is supposed to have a proper in the case of mismatched SVC versions. I can connect to a 1.20.1 server from 1.21 fine, if the version matches, and the error works correctly if the version does not match.

**Comment by FlorianMichael** [comment] 2024-08-19 01:31
@DreiPixel If you can't reproduce this issue without Simple Voice Chat installed, I would recommend you to ask the SVC support for further help.

**Comment by DreiPixel** [comment] 2024-08-20 16:20
> It works for me on a Fabric 1.20.1 server. I'm guessing there might be some issue with Velocity.

mh that might be the issue but i doubt that Velocity will fix anything on their side.

**Comment by FlorianMichael** [comment] 2024-08-20 16:25
You should try if it happens without Velocity in your setup and if so, report it to the Velocity developers. Since there is no evidence of this being an actual ViaFabricPlus issue, I am going to close it for now. Feel free to share any further information you get in this issue anyway.

**Closed by FlorianMichael** 2024-08-20 16:25 UTC
Labels: bug
