### ISSUE TITLE
Unable to launch with openjdk jdk-17.0.0.18-openj9

### ISSUE THREAD

**Issue by EpicestGamer** [ViaVersion/ViaFabricPlus#156] opened 2023-06-25 14:54 UTC
### General Information

ViaFabricPlus
Quilted Fabric API
Quilt Loader

### Bug Description

I'm unable to launch Minecraft using only ViaFabricPlus, Quilted Fabric API, and the Quilt Loader. This is fixed when switching my JRE to the one included with the Java 17 JDK on the Java website, as opposed to AdoptOpenJDK's JDK.

I likely just need to update my AdoptOpenJDK install, so I'm unsure as to if I should even be making a bug report right now, but it may be worth documenting for anyone in the future who has this issue.

[crash-2023-06-25_08.46.17.5485-quilt_loader.txt](https://github.com/ViaVersion/ViaFabricPlus/files/11860014/crash-2023-06-25_08.46.17.5485-quilt_loader.txt)

### Steps to Reproduce

1. Try launching Minecraft

### Expected Behavior

The game should launch.

**Comment by FlorianMichael** [comment] 2023-06-25 15:00
Can you try if it works with normal Fabric?

**Comment by TurklerRS** [comment] 2023-07-07 00:10
bug is about two weeks old but I wanted to throw in some help. I couldn't replicate this issue on normal fabric, but it does consistently happen on quilt. the problem is the quilt team is slowly moving further and further away from supporting fabric and it'd be a fruitless task to try and maintain quilt compatibility.

**Comment by FlorianMichael** [comment] 2023-07-07 14:31
I already suspected that, then this is probably a quilt-only issue again and so I'll close this issue here for now, you can report the error at Quilt

**Closed by FlorianMichael** 2023-07-07 14:31 UTC
Labels: bug
