### ISSUE TITLE
Unable to connect to a 1.20.2 Fabric server w/ Fabric API installed with a 1.20.1 client.

### ISSUE THREAD

**Issue by Tyde5969** [ViaVersion/ViaFabricPlus#260] opened 2023-10-03 20:43 UTC
### General Information

Client mods: Fabric API & ViaFabricPlus
Server Mods: Fabric API

### Bug Description

Unable to connect to a server with Fabric API installed.
My client version is in 1.20.1 while the server version is in 1.20.2.
I can connect to a vanilla server or a fabric server without the fabric API mod.

This is the error I get when attempting to connect to a fabric server with the fabric API installed on it
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/44074308/4147d445-1558-4bfe-aa89-4c8bf7fed09f)

### Steps to Reproduce

1. Create a Fabric 1.20.2 server with Fabric API installed and have it running
2. Create an instance of Minecraft 1.20.1 with Fabric API & ViaFabricPlus installed
3. Attempt to connect to the server.

### Expected Behavior

I should be able to successfully connect to the server regardless of if the Fabric API is installed on the server.

**Comment by FlorianMichael** [comment] 2023-10-03 20:45
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/257, read the conversation for more information/how to fix.

**Closed** 2023-10-03 20:45 UTC
Labels: bug

**Comment by Tyde5969** [comment] 2023-10-04 01:54
Hi put the ViaVersion & ViaBackwards in ViaFabricPlus\jars but I'm still getting the same error.

**Comment by FlorianMichael** [comment] 2023-10-04 01:55
Did you installed the dev or release jar files?

**Comment by Tyde5969** [comment] 2023-10-04 01:56
release

**Comment by FlorianMichael** [comment] 2023-10-04 01:56
Does it work on a non-Fabric server (e.g. Spigot,Vanilla,Paper,Purpur) ?

**Comment by Tyde5969** [comment] 2023-10-04 02:01
I've tested it on vanilla and fabric. it works in vanilla. It will only work on fabric as long as the fabric API is not in the mods list.

**Comment by FlorianMichael** [comment] 2023-10-04 02:05
Yeah, Fabric servers in general aren't really supported atm.

**Comment by Tyde5969** [comment] 2023-10-04 02:13
Ah got it. bummer. well, thank you for your time.

**Comment by FlorianMichael** [comment] 2023-10-04 02:14
I will notify you as soon as I fix it.

**Comment by Tyde5969** [comment] 2023-10-04 02:16
Thanks man. Have a good day.
